seed: 1234567890
global: 
  checkpoint_dir: ".checkpoints/dqn-pong"
  should_save: true
  should_load: true
  max_episodes: 10000
  batch_size: 16

  n_steps: 1
  gamma: 1.

environment:
  path: asrel.environments.gym
  num_workers: 2
  num_envs_per_worker: 3
  conf:
    id: Pong-v0
    wrappers:
    - path: asrel.environments.gym.wrappers.atari_observation
      conf:
        crop: [30, 210]
    - path: asrel.environments.gym.wrappers.frame_history
      conf:
        history_len: 4
    - path: asrel.environments.gym.wrappers.frame_skip
      conf:
        skip_len: 4
    # - path: asrel.environments.gym.wrappers.total_score
    # - path: asrel.environments.gym.wrappers.unit_reward

actor:
  path: asrel.actors.discrete.greedy
  num_workers: 1
  conf: 
    device: cuda
    net:
      path: asrel.networks.simple_conv2d
      conf:
        conv_params:
        - out_channels: 32
          kernel_size: 8
          stride: 4
        - out_channels: 64
          kernel_size: 4
          stride: 2
        - out_channels: 64
          kernel_size: 3
          stride: 1
        ff_layers: [128]

store:
  path: asrel.stores.exp_replay
  class: ExperienceReplay
  buffer_size: 16
  warmup_steps: 1024
  conf: 
    maxsize: 10000
    types:
      action: int32

learner:
  path: asrel.learners.classic.dqn
  conf:
    device: cuda
    net:
      path: asrel.networks.simple_conv2d
      conf:
        conv_params:
        - out_channels: 32
          kernel_size: 8
          stride: 4
        - out_channels: 64
          kernel_size: 4
          stride: 2
        - out_channels: 64
          kernel_size: 3
          stride: 1
        ff_layers: [128]
        optimizer:
          name: Adam
          lr: 1.e-3
    
    epsilon: 1.e-3
    epsilon_dec: 1.e-4
    epsilon_end: 1.e-3
    use_hard_update: false
    tau: 5.e-3
    
    policy_update_freq: 1000

orchestrator:
  pipelines:
    - path: asrel.pipelines.observation.standard
      conf:
        batch_split: 3
    - path: asrel.pipelines.action.standard
    - path: asrel.pipelines.dataset.standard
    - path: asrel.pipelines.policy.standard

registry:
  shared:
    environment: false
    actor: true
