orchestrator:
  max_episodes: 1000
  queue_timeout: 60
  has_shared_env_queue: false
  split_env_processing: 2

environment:
  path: gym.atari
  num_workers: 4
  num_envs_per_worker: 2
  conf:
    id: Acrobot-v1

actor:
  path: discrete.greedy
  num_workers: 1
  conf: 
    device: cuda

    net:
      path: feed_forward
      conf:
        hidden_layers: [256, 256]

seed: 1234567890