environment:
  path: gym.atari
  num_workers: 2
  num_envs_per_worker: 2
  max_episodes: 1
  conf:
    id: Pong-v0

actor:
  path: discrete.greedy
  num_workers: 2
  conf: 
    device: cuda

    net:
      path: feed_forward
      conf:
        input_size: [2]
        output_size: [4]
        hidden_layers: [256, 256]

seed: 1234567890