environment:
  path: gym.atari
  num_workers: 2
  num_envs_per_worker: 2
  max_episodes: 1
  conf:
    id: Acrobot-v1

actor:
  path: discrete.greedy
  num_workers: 1
  conf: 
    device: cuda

    net:
      path: feed_forward
      conf:
        hidden_layers: [256, 256]

seed: 1234567890