ENV_INTERACT_TASK = "ENV_INTERACT_TASK"

ACTOR_CHOOSE_ACTION_TASK = "ACTOR_CHOOSE_ACTION_TASK"
ACTOR_SYNC_NETWORKS_TASK = "ACTOR_SYNC_NETWORKS_TASK"
ACTOR_UPDATE_PARAMS_TASK = "ACTOR_UPDATE_PARAMS_TASK"

STORE_ADD_EXPERIENCE_TASK = "STORE_ADD_EXPERIENCE_TASK"

LEARNER_TRAIN_TASK = "LEARNER_TRAIN_TASK"

WORKER_TERMINATE_TASK = "WORKER_TERMINATE_TASK"

RETURNED_OBSERVATION_EVENT = "RETURNED_OBSERVATION_EVENT"
RETURNED_ACTION_EVENT = "RETURNED_ACTION_EVENT"
RETURNED_BATCH_DATA_EVENT = "RETURNED_BATCH_DATA_EVENT"
RETURNED_NETWORK_UPDATE_EVENT = "RETURNED_NETWORK_UPDATE_EVENT"
RETURNED_ACTOR_UPDATE_EVENT = "RETURNED_ACTOR_UPDATE_EVENT"

