ENV_INTERACT_TASK = "ENV_INTERACT_TASK"

ACTOR_CHOOSE_ACTION_TASK = "ACTOR_CHOOSE_ACTION_TASK"
ACTOR_SYNC_NETWORKS_TASK = "ACTOR_SYNC_NETWORKS_TASK"
ACTOR_UPDATE_PARAMS_TASK = "ACTOR_UPDATE_PARAMS_TASK"

RETURNED_OBSERVATION_EVENT = "RETURNED_OBSERVATION_EVENT"
RETURNED_ACTION_EVENT = "RETURNED_ACTION_EVENT"
